### ISSUE TITLE
Can you add relevant scripts for your polybar conifg

### ISSUE THREAD

**Issue by PittacusOfLorien** [pavanjadhaw/etc#1]
(ie. 2bws.sh, playpause.sh)

**Comment by pavanjadhaw** [comment]
@PittacusOfLorien yeah sure, I just started with 2bwm so I dont have my own and thats sole reason I havent added them yet.
I am using one by NerdyPepper and you can find them ![here](https://github.com/NerdyPepper/dotfiles/tree/master/scripts/scripts)

**Comment by PittacusOfLorien** [comment]
Thanks
